// components/RootLayout.js
import Head from 'next/head';
import { Inter } from 'next/font/google';
import './globals.css'
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <Head>
      {/* Add other head elements as needed */}
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content={metadata.description} />
      <title>{metadata.title}</title>
      {/* Include Font Awesome stylesheet */}
 
      {/* Include global styles */}
      <link rel="stylesheet" href="./globals.css" />
    </Head>
    <body className={inter.className}>     <link
        rel="stylesheet"
        href="https://pro.fontawesome.com/releases/v6.0.0-beta2/css/all.css"
        integrity="your-integrity-hash"
        crossOrigin="anonymous"
      />
      {/* Include Font Awesome script */}
      <script
        src="https://use.fortawesome.com/349cfdf6.js"
        integrity="your-integrity-hash"
        crossOrigin="anonymous"
      ></script>{children}</body>
  </html>
);

export default RootLayout;
